### PR TITLE
romanian translation for Mi Tools

### PR DESCRIPTION
**Pull request by ygorigor**

### CODE REVIEW

**Comment by ygorigor** [comment]
Can you tell me where I can find a instruction how to create a server for holidays.
Thanks in advance

**Comment by ghost** [comment]
this will help ? : https://github.com/BurgerZ/WSM-Project/issues/4

**Comment by ygorigor** [comment]
Can I hold file holidays-ro-rMD.jsp here on github?

**Comment by zdunex25** [comment]
Holidays in Poland: http://roms.miuipolska.pl/zdunex25/wip/holidays-pl.jsp

**Pull request merged**
